export const VIEW_FILE_FAIL = 'VIEW_FILE_FAIL';
export const VIEW_FILE_REQUEST = 'VIEW_FILE_REQUEST';
export const VIEW_FILE_SUCCESS = 'VIEW_FILE_SUCCESS';

export const IPFS_REQUEST = 'IPFS_REQUEST';
export const IPFS_REQUEST_FAIL = 'IPFS_REQUEST_FAIL';
export const IPFS_REQUEST_SUCCESS = 'IPFS_REQUEST_SUCCESS';