export const MINT_CREATE_REQUEST = 'MINT_CREATE_REQUEST';
export const MINT_CREATE_SUCCESS = 'MINT_CREATE_SUCCESS';
export const MINT_CREATE_FAIL = 'MINT_CREATE_FAIL';
export const MINT_CREATE_RESET = 'MINT_CREATE_RESET';

export const MINT_MINT_REQUEST = 'MINT_MINT_REQUEST';
export const MINT_MINT_SUCCESS = 'MINT_MINT_SUCCESS';
export const MINT_MINT_FAIL = 'MINT_MINT_FAIL';
export const MINT_MINT_RESET = 'MINT_MINT_RESET';

export const MINT_DETAILS_REQUEST = 'MINT_DETAILS_REQUEST';
export const MINT_DETAILS_SUCCESS = 'MINT_DETAILS_SUCCESS';
export const MINT_DETAILS_FAIL = 'MINT_DETAILS_FAIL';

export const MINT_MINE_LIST_REQUEST = 'MINT_MINE_LIST_REQUEST';
export const MINT_MINE_LIST_SUCCESS = 'MINT_MINE_LIST_SUCCESS';
export const MINT_MINE_LIST_FAIL = 'MINT_MINE_LIST_FAIL';

export const MINT_LIST_REQUEST = 'MINT_LIST_REQUEST';
export const MINT_LIST_SUCCESS = 'MINT_LIST_SUCCESS';
export const MINT_LIST_FAIL = 'MINT_LIST_FAIL';

export const MINT_DELETE_REQUEST = 'MINT_DELETE_REQUEST';
export const MINT_DELETE_SUCCESS = 'MINT_DELETE_SUCCESS';
export const MINT_DELETE_FAIL = 'MINT_DELETE_FAIL';
export const MINT_DELETE_RESET = 'MINT_DELETE_RESET';

export const MINT_SUMMARY_REQUEST = 'MINT_SUMMARY_REQUEST';
export const MINT_SUMMARY_SUCCESS = 'MINT_SUMMARY_SUCCESS';
export const MINT_SUMMARY_FAIL = 'MINT_SUMMARY_FAIL';
